spring.application.name=APIGateway
server.port=8083

# Eureka
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=false
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

## =========================
## ASERVICE
## =========================
#spring.cloud.gateway.routes[0].id=aservice-route
#spring.cloud.gateway.routes[0].uri=lb://ASERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/A/**
#spring.cloud.gateway.routes[0].filters.name=RequestRateLimiter
#spring.cloud.
## =========================
## BSERVICE
## =========================
#spring.cloud.gateway.routes[1].id=bservice-route
#spring.cloud.gateway.routes[1].uri=lb://BSERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/B/**
#
#spring.cloud.gateway.routes[2].id=bservice-route
#spring.cloud.gateway.routes[2].uri=lb://BSERVICE
#spring.cloud.gateway.routes[2].predicates[0]=Path=/BA/**
#
