spring.application.name=BSERVICE

server.port=8082
eureka.client.service-url.defaultZone = http://localhost:8081/eureka

eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=false

spring.profiles.active=dev
valueFromProp= valuefromproop