spring.application.name=BSERVICE

server.port=8082
eureka.client.service-url.defaultZone = http://localhost:8081/eureka

eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=false

resilience4j.ratelimiter.instances.BService.limit-for-period=3
resilience4j.ratelimiter.instances.BService.limit-refresh-period=100s
resilience4j.ratelimiter.instances.BService.timeout-duration=0s


resilience4j.ratelimiter.instances.ABService.limit-for-period=5
resilience4j.ratelimiter.instances.ABService.limit-refresh-period=100s
resilience4j-ratelimiter.instances.ABService.timeout-duration=100s

spring.profiles.active = prod