spring.application.name=ASERVICE
server.port=8090
eureka.client.service-url.defaultZone = http://localhost:8081/eureka
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=false